### PR TITLE
Fix links to yaml.org

### PR DESCRIPTION
**Pull request by aureliojargas**
It seems the www domain stopped working.
Also, it is now served as https by default.

### CODE REVIEW

**Comment by aureliojargas** [comment]
FYI: I've also opened an issue for them, since it seems a site configuration bug: https://github.com/yaml/www.yaml.org/issues/46

**Comment by wolfgang42** [comment]
Thanks, I'll deploy this tonight and keep an eye on the bug you filed to see what the final resolution is.

**Comment by ingydotnet** [comment]
The www.yaml.org dns issue has been resolved.

**Comment by wolfgang42** [comment]
Looks like https://yaml.org is the canonical URL anyway (they've dropped the www. and added the s) so I'll merge in your change. Thanks again!

**Pull request merged**
